-- Eliminar la base de datos si existe
DROP DATABASE IF EXISTS db_sql_Martinez;

-- Crear la base de datos
CREATE DATABASE db_sql_Martinez;

-- Usar la base de datos
USE db_sql_Martinez;

-- Eliminar tablas si existen
DROP TABLE IF EXISTS HISTORIAL_EMPLEOS;
DROP TABLE IF EXISTS EMPLEADOS;
DROP TABLE IF EXISTS EMPLEOS;
DROP TABLE IF EXISTS DEPARTAMENTOS;
DROP TABLE IF EXISTS DIRECCIONES;
DROP TABLE IF EXISTS PROVINCIA;
DROP TABLE IF EXISTS PAIS;

-- Crear tablas
CREATE TABLE PAIS (
    ID_PAIS VARCHAR(3) NOT NULL,
    NOMBRE_PAIS VARCHAR(40),
    PRIMARY KEY (ID_PAIS)
);

CREATE TABLE PROVINCIA (
    ID_PROVINCIA INT NOT NULL AUTO_INCREMENT,
    NOMBRE_PROVINCIA VARCHAR(35) NOT NULL,
    ID_PAIS VARCHAR(3),
    PRIMARY KEY (ID_PROVINCIA),
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);

CREATE TABLE DIRECCIONES (
    ID_DIRECCION INT NOT NULL AUTO_INCREMENT,
    DIRECCION VARCHAR(40),
    CODIGO_POSTAL VARCHAR(12),
    CIUDAD VARCHAR(30) NOT NULL,
    ID_PAIS VARCHAR(3),
    ID_PROVINCIA INT, 
    PRIMARY KEY (ID_DIRECCION),
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS),
    FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA)
);

CREATE TABLE DEPARTAMENTOS (
    ID_DEPARTAMENTO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_DEPARTAMENTO VARCHAR(30) NOT NULL,
    ID_JEFE INT,
    ID_DIRECCION INT,
    PRIMARY KEY (ID_DEPARTAMENTO),
    FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCIONES(ID_DIRECCION)
);

CREATE TABLE EMPLEOS (
    ID_EMPLEO VARCHAR(10) NOT NULL,
    TITULO_EMPLEO VARCHAR(35) NOT NULL,
    SALARIO_MINIMO DECIMAL(10, 2),
    SALARIO_MAXIMO DECIMAL(10, 2),
    PRIMARY KEY (ID_EMPLEO)
);

CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(20),
    APELLIDO VARCHAR(25) NOT NULL,
    CORREO VARCHAR(25) NOT NULL,
    TELEFONO VARCHAR(20),
    FECHA_CONTRATACION DATE NOT NULL,
    ID_EMPLEO VARCHAR(10),
    SALARIO DECIMAL(10, 2),
    PORCENTAJE_COMISION DECIMAL(5, 2),
    ID_JEFE INT,
    ID_DEPARTAMENTO INT,
    PRIMARY KEY (ID_EMPLEADO),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO),
    FOREIGN KEY (ID_EMPLEO) REFERENCES EMPLEOS(ID_EMPLEO),
    FOREIGN KEY (ID_JEFE) REFERENCES EMPLEADOS(ID_EMPLEADO)
);

CREATE TABLE HISTORIAL_EMPLEOS (
    ID_EMPLEADO INT NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    ID_EMPLEO VARCHAR(10) NOT NULL,
    ID_DEPARTAMENTO INT,
    PRIMARY KEY (ID_EMPLEADO, FECHA_INICIO),
    FOREIGN KEY (ID_EMPLEO) REFERENCES EMPLEOS(ID_EMPLEO),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO)
);